config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.api.urls')),
]

project/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from ..views import CharactersCreateView, CharactersListView
from .viewsets import CharacterViewset

router = DefaultRouter()
router.register('characters', CharacterViewset)

urlpatterns = [
  path('api/',include(router.urls)),
  path('', CharactersCreateView.as_view(), name="home"),
  path('list/', CharactersListView.as_view(), name="characters_list")
]

project/models.py
from django.db import models


class Character(models.Model):
  name = models.CharField(max_length=60)
  status = models.CharField(max_length=30)
  species = models.CharField(max_length=60)
  char_type = models.CharField(max_length=80)
  gender = models.CharField(max_length=30)
  image = models.TextField()

  def __str__(self) -> str:
    return f"{self.name} - {self.status}"

project/views.py
from django.http import HttpRequest, HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView

from .api.viewsets import CharacterViewset
from .models import Character


class CharactersCreateView(CreateView):
  model = Character
  template_name = 'character/home.html'
  fields = ['name']
  success_url = reverse_lazy('characters_list')


  def post(self, request: HttpRequest, *args: str, **kwargs: reverse_lazy) -> HttpResponse:
    return super().post(request, *args, **kwargs)

class CharactersListView(ListView):
  model = Character
  template_name = 'character/list.html'
  queryset = Character.objects.all()

project/templates/character/home.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Home</title>
  </head>
  <body>
    <header
      class="w-full h-[3.75rem] bg-green-500 flex items-center justify-center fixed top-0 z-1"
    >
      <nav class="w-[90%] h-full flex items-center justify-between">
        <div class="font-bold text-xl">
          <h3>Home</h3>
        </div>
        <ul>
          <li>
            <a
              href="{% url 'characters_list' %}"
              class="border rounded px-4 py-1 bg-green-700 transition-colors hover:bg-green-600 text-white font-semibold"
              >List</a
            >
          </li>
        </ul>
      </nav>
    </header>
    <main class="h-screen w-full flex items-center justify-center">
      <form
        action=""
        method="post"
        class="border roudend py-6 px-4 flex flex-col items-center bg-neutral-100 gap-4"
      >
        {% csrf_token %}
        <h3 class="w-full text-2xl font-bold text-green-800">
          Regist Character
        </h3>
        {{ form }}
        {{ from.errors }}
        <button
          type="submit"
          class="w-2/5 bg-green-700 rounded py-2 px-4 text-white font-semibold transition-colors hover:bg-green-600"
        >
          Regist
        </button>
      </form>
    </main>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

project/templates/character/list.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Characters List</title>
  </head>
  <body>
    <header
      class="w-full h-[3.75rem] bg-green-500 flex items-center justify-center fixed top-0 z-1"
    >
      <nav class="w-[90%] h-full flex items-center justify-between">
        <div class="font-bold text-xl">
          <h3>Characters List</h3>
        </div>
        <ul>
          <li>
            <a
              href="{% url 'home' %}"
              class="border rounded px-4 py-1 bg-green-700 transition-colors hover:bg-green-600 text-white font-semibold"
              >Home</a
            >
          </li>
        </ul>
      </nav>
    </header>
    <main class="w-full mt-20 flex justify-center">
      <ul class="w-[90%] flex flex-wrap justify-between">
        {% if character_list|length == 0 %}
        <h3
          class="w-[24.5%] font-bold mb-4 p-4 border rounded-md flex flex-col items-center bg-green-600"
        >
          No characters found
        </h3>
        {% else %} {% for character in character_list %}
        <li
          class="w-[24.5%] mb-4 p-4 border rounded-md flex flex-col items-center gap-2 bg-green-600"
        >
          <img
            src="{{ character.image }}"
            alt="{{character.name}}"
            class="rounded-md"
          />
          <span class="w-full font-semibold truncate"
            >Name: {{ character.name }}</span
          >
          <span class="w-full font-semibold"
            >Status: {{ character.status }}</span
          >
          <span class="w-full font-semibold truncate"
            >Type: {{ character.char_type }}</span
          >
          <span class="w-full font-semibold truncate"
            >Especies: {{ character.species }}</span
          >
          <span class="w-full font-semibold truncate"
            >Gender: {{ character.gender }}</span
          >
        </li>
        {% endfor %} {% endif %}
      </ul>
    </main>
  </body>
</html>